
[trainer]
gpus: 1
min_epochs: 1
max_epochs: 5,5,5,5,5,5,5,5,5,5
auto_lr_find: True
auto_scale_batch_size: False
precision: 16
max_time: 00:23:50:00

[model]
loss: focal 
segmentation_model: unet
backbone: resnet50
learning_rate: 1e-3
pretrained: True
learning_rate_schedule_patience: 10
encoder_weights: imagenet  
num_classes: 3


[datamodule]
batch_size: 4
num_workers: 2

[cl]
mode: cl
patch_size: 128
stride: 90
extract: True
max_nr_patches: 7
var_list: TMQ,U850,V850,PRECT
nr_stages: 10


[logging]
log_nr: balance_patches