
[trainer]
gpus: 1
min_epochs: 1
max_epochs: 20
auto_lr_find: True
auto_scale_batch_size: False
precision: 16
max_time: 00:23:50:00

[model]
loss: focal 
segmentation_model: deeplabv3+
backbone: resnet50
learning_rate: 1e-3
pretrained: True
learning_rate_schedule_patience: 5
encoder_weights: imagenet  
num_classes: 3


[datamodule]
batch_size: 4
num_workers: 2

[cl]
extract: False
max_nr_patches: 5
var_list: TMQ,U850,V850,PRECT
events: background,single_ar,single_tc,mixed,random
patch_size: 150
stride: 50

[logging]
log_nr: 20