name: tcd
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bokeh=2.4.3
  - bottleneck=1.3.5
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.9.24
  - certifi=2022.9.24
  - cffi=1.15.1
  - cftime=1.5.1.1
  - charset-normalizer=2.0.4
  - click=8.1.3
  - cloudpickle=2.2.0
  - cryptography=37.0.1
  - cudatoolkit=11.3.1
  - curl=7.84.0
  - cytoolz=0.12.0
  - dask=2022.10.2
  - dask-core=2022.10.2
  - distributed=2022.10.2
  - ffmpeg=4.3
  - freetype=2.11.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - hdf4=4.2.13
  - hdf5=1.10.6
  - heapdict=1.0.1
  - idna=3.4
  - intel-openmp=2021.4.0
  - jinja2=3.1.2
  - jpeg=9e
  - keyutils=1.6.1
  - krb5=1.19.3
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcurl=7.84.0
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libnetcdf=4.6.1
  - libnghttp2=1.46.0
  - libpng=1.6.37
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - locket=1.0.0
  - lz4=3.1.3
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - msgpack-python=1.0.3
  - ncurses=6.3
  - netcdf4=1.5.7
  - nettle=3.7.3
  - numexpr=2.8.3
  - numpy=1.23.3
  - numpy-base=1.23.3
  - openh264=2.1.1
  - openssl=1.1.1s
  - packaging=21.3
  - partd=1.3.0
  - pillow=9.2.0
  - pip=22.2.2
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.10.6
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - pytz=2022.6
  - pyyaml=6.0
  - readline=8.1.2
  - requests=2.28.1
  - setuptools=63.4.1
  - six=1.16.0
  - sortedcontainers=2.4.0
  - sqlite=3.39.3
  - tblib=1.7.0
  - tk=8.6.12
  - toolz=0.12.0
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - typing_extensions=4.3.0
  - tzdata=2022e
  - urllib3=1.26.12
  - wheel=0.37.1
  - xarray=2022.11.0
  - xz=5.2.6
  - yaml=0.2.5
  - zict=2.2.0
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - absl-py==1.3.0
    - affine==2.3.1
    - aiohttp==3.8.3
    - aiosignal==1.2.0
    - antlr4-python3-runtime==4.9.3
    - anyio==3.6.2
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.0.8
    - async-timeout==4.0.2
    - attrs==22.1.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - black==22.3.0
    - bleach==5.0.1
    - cachetools==5.2.0
    - cfgv==3.3.1
    - click-plugins==1.1.1
    - cligj==0.7.2
    - contourpy==1.0.5
    - cycler==0.11.0
    - debugpy==1.6.3
    - decorator==5.1.1
    - defusedxml==0.7.1
    - detectron2==0.6
    - distlib==0.3.6
    - docker-pycreds==0.4.0
    - dotmap==1.3.30
    - efficientnet-pytorch==0.7.1
    - einops==0.4.1
    - entrypoints==0.4
    - executing==1.1.1
    - fairscale==0.4.12
    - fastjsonschema==2.16.2
    - filelock==3.8.0
    - fiona==1.8.22
    - fonttools==4.37.4
    - frozenlist==1.3.1
    - fsspec==2022.10.0
    - future==0.18.2
    - fvcore==0.1.5.post20220512
    - gitdb==4.0.9
    - gitpython==3.1.29
    - google-auth==2.13.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.50.0
    - hydra-core==1.2.0
    - identify==2.5.6
    - imageio==2.22.2
    - iopath==0.1.9
    - ipykernel==6.16.1
    - ipython==8.5.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.2
    - isort==5.10.1
    - jedi==0.18.1
    - joblib==1.2.0
    - jsonschema==4.16.0
    - jupyter==1.0.0
    - jupyter-client==7.4.3
    - jupyter-console==6.4.4
    - jupyter-core==4.11.2
    - jupyter-server==1.21.0
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.3
    - kiwisolver==1.4.4
    - kornia==0.6.8
    - markdown==3.4.1
    - matplotlib==3.6.2
    - matplotlib-inline==0.1.6
    - mistune==2.0.4
    - multidict==6.0.2
    - munch==2.5.0
    - mypy-extensions==0.4.3
    - nb-clean==2.3.0
    - nbclassic==0.4.5
    - nbclient==0.7.0
    - nbconvert==7.2.2
    - nbformat==5.7.0
    - nest-asyncio==1.5.6
    - networkx==2.8.7
    - nodeenv==1.7.0
    - notebook==6.5.1
    - notebook-shim==0.2.0
    - oauthlib==3.2.2
    - omegaconf==2.2.3
    - opencv-contrib-python==4.6.0.66
    - opencv-python-headless==4.6.0.66
    - pandas==1.5.1
    - pandocfilters==1.5.0
    - parso==0.8.3
    - patchify==0.2.3
    - pathspec==0.10.1
    - pathtools==0.1.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - platformdirs==2.5.2
    - plotly==5.11.0
    - portalocker==2.6.0
    - pre-commit==2.20.0
    - pretrainedmodels==0.7.4
    - prometheus-client==0.15.0
    - promise==2.3
    - prompt-toolkit==3.0.31
    - protobuf==3.19.6
    - psutil==5.9.3
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocotools==2.0.5
    - pydantic==1.10.2
    - pydeprecate==0.3.2
    - pydot==1.4.2
    - pygments==2.13.0
    - pyproj==3.4.0
    - pyrsistent==0.18.1
    - python-decouple==3.6
    - python-dotenv==0.21.0
    - pytorch-lightning==1.7.7
    - pywavelets==1.4.1
    - pyzmq==24.0.1
    - qtconsole==5.3.2
    - qtpy==2.2.1
    - rasterio==1.3.3
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - rtree==1.0.1
    - scikit-image==0.19.3
    - scikit-learn==1.1.2
    - scipy==1.9.3
    - seaborn==0.12.1
    - segmentation-models-pytorch==0.3.0
    - send2trash==1.8.0
    - sentry-sdk==1.10.1
    - setproctitle==1.3.2
    - shapely==1.8.5.post1
    - shortuuid==1.0.9
    - smmap==5.0.0
    - sniffio==1.3.0
    - snuggs==1.4.7
    - soupsieve==2.3.2.post1
    - stack-data==0.5.1
    - tabulate==0.9.0
    - tenacity==8.1.0
    - tensorboard==2.10.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - termcolor==2.0.1
    - terminado==0.16.0
    - threadpoolctl==3.1.0
    - tifffile==2022.10.10
    - timm==0.4.12
    - tinycss2==1.2.1
    - toml==0.10.2
    - tomli==2.0.1
    - torchgeo==0.3.1
    - torchmetrics==0.9.3
    - tornado==6.2
    - tqdm==4.64.1
    - traitlets==5.5.0
    - virtualenv==20.16.5
    - wandb==0.13.4
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.4.1
    - werkzeug==2.2.2
    - widgetsnbextension==4.0.3
    - yacs==0.1.8
    - yarl==1.8.1
