
[path]
data_path: /cluster/work/igp_psr/ai4good/group-1b/data/
repo_path: <path to repository>
log_path: /cluster/scratch/krasnopk/debug_log

[wandb]
log_wandb: False 
entity: debug
project: debug 

[trainer]
gpus: 1
min_epochs: 1
max_epochs: 10
auto_lr_find: True
auto_scale_batch_size: False
precision: 16
max_time: 00:23:50:00

[model]
loss: focal 
segmentation_model: unet
backbone: resnet18
learning_rate: 1e-3
pretrained: True
learning_rate_schedule_patience: 10
encoder_weights: imagenet  
num_classes: 3


[datamodule]
batch_size: 32
num_workers: 1

[cl]
mode: base
patch_size: 128
stride: 90
extract: False
max_nr_patches: 5
var_list: TMQ,U850,V850,PRECT
nr_stages: 20


[logging]
log_nr: <Logging folder for this specific run>