name: cl
channels:
  - conda-forge
  - defaults
dependencies:
  - bokeh=2.4.3
  - bottleneck=1.3.5
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - cffi=1.15.1
  - cftime=1.6.2
  - click=8.1.3
  - cloudpickle=2.2.0
  - cryptography=39.0.0
  - curl=7.86.0
  - cytoolz=0.12.0
  - dask=2022.12.1
  - dask-core=2022.12.1
  - distributed=2022.12.1
  - freetype=2.10.4
  - fsspec=2022.11.0
  - giflib=5.2.1
  - hdf4=4.2.15
  - hdf5=1.12.1
  - heapdict=1.0.1
  - idna=3.4
  - jinja2=3.1.2
  - jpeg=9e
  - krb5=1.19.3
  - lcms2=2.14
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.86.0
  - libcxx=14.0.6
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgfortran5=11.3.0
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libnghttp2=1.46.0
  - libopenblas=0.3.21
  - libpng=1.6.37
  - libssh2=1.10.0
  - libtiff=4.4.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libzip=1.8.0
  - llvm-openmp=15.0.6
  - locket=1.0.0
  - lz4=4.2.0
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - msgpack-python=1.0.4
  - ncurses=6.3
  - netcdf4=1.6.0
  - numpy=1.24.1
  - openssl=1.1.1s
  - pandas=1.5.2
  - partd=1.3.0
  - pillow=9.3.0
  - pip=22.3.1
  - psutil=5.9.4
  - pycparser=2.21
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.10.0
  - python-dateutil=2.8.2
  - python-decouple=3.6
  - python_abi=3.10
  - pytz=2022.7
  - pyyaml=6.0
  - readline=8.2
  - setuptools=65.5.0
  - six=1.16.0
  - sortedcontainers=2.4.0
  - sqlite=3.40.0
  - tblib=1.7.0
  - tk=8.6.12
  - toolz=0.12.0
  - tornado=6.2
  - typing_extensions=4.4.0
  - tzdata=2022g
  - urllib3=1.26.13
  - wheel=0.37.1
  - xarray=2022.12.0
  - xz=5.2.8
  - yaml=0.2.5
  - zict=2.2.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - affine==2.3.1
    - aiohttp==3.8.3
    - aiosignal==1.3.1
    - antlr4-python3-runtime==4.9.3
    - async-timeout==4.0.2
    - attrs==22.2.0
    - charset-normalizer==2.1.1
    - click-plugins==1.1.1
    - cligj==0.7.2
    - contourpy==1.0.6
    - cycler==0.11.0
    - docker-pycreds==0.4.0
    - efficientnet-pytorch==0.7.1
    - einops==0.4.1
    - fiona==1.8.22
    - fonttools==4.38.0
    - frozenlist==1.3.3
    - gitdb==4.0.10
    - gitpython==3.1.30
    - joblib==1.2.0
    - kiwisolver==1.4.4
    - kornia==0.6.9
    - lightning-utilities==0.5.0
    - matplotlib==3.6.2
    - multidict==6.0.4
    - munch==2.5.0
    - omegaconf==2.3.0
    - packaging==21.3
    - patchify==0.2.3
    - pathtools==0.1.2
    - pretrainedmodels==0.7.4
    - promise==2.3
    - protobuf==3.20.1
    - pyparsing==3.0.9
    - pyproj==3.4.1
    - pytorch-lightning==1.8.6
    - rasterio==1.3.4
    - requests==2.28.1
    - rtree==1.0.1
    - scikit-learn==1.2.0
    - scipy==1.10.0
    - segmentation-models-pytorch==0.3.1
    - sentry-sdk==1.12.1
    - setproctitle==1.3.2
    - shapely==1.8.5.post1
    - shortuuid==1.0.11
    - smmap==5.0.0
    - snuggs==1.4.7
    - tensorboardx==2.5.1
    - threadpoolctl==3.1.0
    - timm==0.4.12
    - torch==1.12.1
    - torchgeo==0.3.1
    - torchmetrics==0.9.3
    - torchvision==0.13.1
    - tqdm==4.64.1
    - wandb==0.13.7
    - yarl==1.8.2
